version: '3.9'

services:

  react-ui:
    container_name: react-ui
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - api
    
  api:
    container_name: api
    build: 
      context: ./backend
    image: elections-2022_api
    ports:
      - 8000:8000
    depends_on:
      - mongo
    environment:
      - APP_ENV=docker
    expose:
      - 8000
  

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    environment:
      - APP_ENV=docker
    volumes:
      - './data:/data/db'
    expose:
      - 27017

  redis:
    container_name: redis
    image: redis
    environment:
      - APP_ENV=docker
    expose:
      - 6379
  
  worker:
    container_name: worker
    image: elections-2022_api:latest
    depends_on:
        - redis
    command: rq worker --url redis://redis:6379
    links:
        - redis
  
  collector:
    container_name: collector
    image: elections-2022_api:latest
    command: python backend/app/collector.py
    depends_on:
      - worker
      - mongo
    profiles:
      - collect
