version: '3.1'

services:

  react-ui:
    build:
      context: ../elections-front
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    depends_on:
      - api
    

  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 8000:8000
    depends_on:
      - mongo
      - redis
    container_name: api

  mongo:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo
    volumes:
      - './data:/data/db'

  redis:
    image: redis
    ports:
      - 6379:6379
    expose:
      - 6379
    container_name: redis
  
  worker:
      image: brazilian-elections_api:latest
      depends_on:
          - redis
      command: rq worker --url redis://redis:6379
      links:
          - redis
  
  collector:
      image: brazilian-elections_api:latest
      command: python collect.py
      depends_on:
        - worker
        - mongo
