version: '3.1'

services:

  react-ui:
    container_name: react-ui
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - api
    
  api:
    container_name: api
    build: 
      context: .
      dockerfile: Dockerfile.api
    image: elections-2022_api
    ports:
      - 8000:8000
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - './data:/data/db'

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    expose:
      - 6379
  
  worker:
    container_name: worker
    image: elections-2022_api:latest
    depends_on:
        - redis
    command: rq worker --url redis://redis:6379
    links:
        - redis
  
  collector:
    container_name: collector
    image: elections-2022_api:latest
    command: python collect.py
    depends_on:
      - worker
      - mongo
