[local]
APP_ENV = "local"
REDIS_HOST = "localhost"
REDIS_PORT = 6379
MONGO_HOST = "localhost"
MONGO_PORT = 27017


[docker]
APP_ENV = "docker"
REDIS_HOST = "redis"
REDIS_PORT = 6379
MONGO_HOST = "mongo"
MONGO_PORT = 27017
